### PR TITLE
url validation for JSONP and getZoomify added

### PR DESCRIPTION
**Pull request by bjquast**

### CODE REVIEW

**Comment by aquast** [comment]
Hi Björn, to avoid code-duplication call for SourceValidator should be integrated into private getDziResult method and getZoomifyResult, accordingly. Both will be called by the public methods. 

IMHO as deepzoomer.cfg is opened by  Configuration().getClass().getResourceAsStream(PATH_TO_deepzimmer.cfg) the problem you try to solve is depending on your installation, The Applications-Base directory (Working-Directory) has to be defined at the right place .

**Comment by jschnasse** [comment]
I can only recommend to use the following pattern to load files from class path. I use this pattern for years and so far it works under almost all circumstances.

`Thread.currentThread().getContextClassLoader().getResourceAsStream("conf/deepzoomer.cfg")`

**Comment by bjquast** [comment]
Have put that into getDziResult / getZoomifyResult, but perhaps it should end up in SourceValidator

The deepzoomer.cfg link was just changed to a relative path by me. It appears to be useless as the source compiles with or without it. I guess its just an old remain.

**Comment by aquast** [comment]
Ok, unfortunately I found out the place to check for specific domain is completely wrong. I haven't workes on it for too long... Please give me some space to review the both (@bjquast , @jschnasse ) pull requests thouroghly.
@jschnasse: Thread.currentThread().getContextClassLoader().getResourceAsStream("conf/deepzoomer.cfg") is already done so far.

**Comment by bjquast** [comment]
Resolved merge conflict, was just an empty line

**Pull request closed without merging**
